run:
  timeout: 2m # newt build can be quite slow
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - goimports
    - revive
    - misspell
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - linters:
        - revive
      text: ".*and that stutters; consider calling this.*"
